//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int Id { get; set; }
        public string UserID { get; set; }
        public string EmailAddress { get; set; }
        public string ResponseCode { get; set; }
        public string Response { get; set; }
        public System.DateTime PostedOn { get; set; }
        public string Action { get; set; }
        public string Module { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
