//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BurglaryPayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BurglaryPayment()
        {
            this.BurglaryRenewals = new HashSet<BurglaryRenewal>();
            this.BurglaryUserPolicies = new HashSet<BurglaryUserPolicy>();
        }
    
        public int ID { get; set; }
        public string UserID { get; set; }
        public string txtRef { get; set; }
        public Nullable<int> QuoteID { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string AmountString { get; set; }
        public string Payref { get; set; }
        public string RetRef { get; set; }
        public string ResponseCode { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<bool> status { get; set; }
        public string ResponseText { get; set; }
        public Nullable<bool> IsRenewal { get; set; }
        public Nullable<bool> Isdeleted { get; set; }
        public string PolicyNo { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual BurglaryQuote BurglaryQuote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BurglaryRenewal> BurglaryRenewals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BurglaryUserPolicy> BurglaryUserPolicies { get; set; }
    }
}
