//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimsDocument
    {
        public int Id { get; set; }
        public int ClaimId { get; set; }
        public string FileName1 { get; set; }
        public string FileType1 { get; set; }
        public byte[] ClaimDocument1 { get; set; }
        public string FileName2 { get; set; }
        public string FileType2 { get; set; }
        public byte[] ClientDocument2 { get; set; }
        public Nullable<bool> IsAchived { get; set; }
    
        public virtual UserClaim UserClaim { get; set; }
    }
}
