//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimsLife
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string PolicyNo { get; set; }
        public Nullable<System.DateTime> DeathDate { get; set; }
        public string ProductName { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> PostedOn { get; set; }
        public string Reference { get; set; }
    }
}
