//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceQuote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeviceQuote()
        {
            this.DevicePayments = new HashSet<DevicePayment>();
            this.DeviceRenewals = new HashSet<DeviceRenewal>();
            this.DeviceUserPolicies = new HashSet<DeviceUserPolicy>();
        }
    
        public int Id { get; set; }
        public string UserId { get; set; }
        public string Class { get; set; }
        public string DeviceType { get; set; }
        public string Imei { get; set; }
        public string CoverType { get; set; }
        public string SerialNo { get; set; }
        public string DeviceModel { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string AmountValueString { get; set; }
        public Nullable<decimal> Premium { get; set; }
        public string PremiumString { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public Nullable<bool> IsRenewal { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> CanPay { get; set; }
        public string Referral { get; set; }
        public string Name { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevicePayment> DevicePayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceRenewal> DeviceRenewals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceUserPolicy> DeviceUserPolicies { get; set; }
    }
}
