//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceDocument
    {
        public int ID { get; set; }
        public int QuoteID { get; set; }
        public string IdType { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public string FileNameLicence { get; set; }
        public string FileTypeLicence { get; set; }
        public bool IsAchived { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
