//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceClaim
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string PolicyNo { get; set; }
        public Nullable<System.DateTime> DateLoss { get; set; }
        public string Location { get; set; }
        public string Name { get; set; }
        public string DeviceType { get; set; }
        public string Model { get; set; }
        public Nullable<System.DateTime> PostedOn { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
