//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DstvTransaction
    {
        public int Id { get; set; }
        public int Subscriber_id { get; set; }
        public int DstvPremiumDetailsId { get; set; }
        public string TransactionRef { get; set; }
        public decimal Amount { get; set; }
        public string Hash { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string PaymentStatus { get; set; }
    }
}
