//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DstvTransactionPaymentsDetail
    {
        public int Id { get; set; }
        public string Subscriber_id { get; set; }
        public string DstvPremiumDetailsId { get; set; }
        public string txtRef { get; set; }
        public string Payref { get; set; }
        public string RetRef { get; set; }
        public string ResponseCode { get; set; }
        public decimal Amount { get; set; }
        public string AmountString { get; set; }
        public string Description { get; set; }
        public string status { get; set; }
        public string ResponseText { get; set; }
        public string IsRenewal { get; set; }
        public string PolicyNo { get; set; }
        public string Hash { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
