//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DstvPremiumDetail
    {
        public int Id { get; set; }
        public int DstvSubscriberId { get; set; }
        public string DstvPolicy { get; set; }
        public decimal SumInsured { get; set; }
        public string AnnualEmolument { get; set; }
        public string AssetDescription { get; set; }
        public string VehicleReg { get; set; }
        public string Chasis { get; set; }
        public string EngineNumbers { get; set; }
        public string HomeType { get; set; }
        public string PersonalAccident { get; set; }
        public System.DateTime creeated_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string VehicleDate { get; set; }
        public string VehicleMake { get; set; }
        public string VehicleModel { get; set; }
        public string Location { get; set; }
        public string PromoCode { get; set; }
    }
}
