//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationTable
    {
        public int Id { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<decimal> Term5 { get; set; }
        public Nullable<decimal> Term6 { get; set; }
        public Nullable<decimal> Term7 { get; set; }
        public Nullable<decimal> Term8 { get; set; }
        public Nullable<decimal> Term9 { get; set; }
        public Nullable<decimal> Term10 { get; set; }
        public Nullable<decimal> Term11 { get; set; }
        public Nullable<decimal> Term12 { get; set; }
        public Nullable<decimal> Term13 { get; set; }
        public Nullable<decimal> Term14 { get; set; }
        public Nullable<decimal> Term15 { get; set; }
    }
}
