//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LifeUserPolicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LifeUserPolicy()
        {
            this.LifeRenewals = new HashSet<LifeRenewal>();
        }
    
        public int ID { get; set; }
        public string UserID { get; set; }
        public int PaymentID { get; set; }
        public Nullable<int> LifeQuoteID { get; set; }
        public string PolicyNumber { get; set; }
        public string Name { get; set; }
        public string txtRef { get; set; }
        public string Certificate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsApprovedbyNsia { get; set; }
        public Nullable<System.DateTime> ParentExpiryDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual LifePayment LifePayment { get; set; }
        public virtual LifeQuote LifeQuote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LifeRenewal> LifeRenewals { get; set; }
    }
}
