//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LifeQuote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LifeQuote()
        {
            this.InvUserPolicies = new HashSet<InvUserPolicy>();
            this.LifePayments = new HashSet<LifePayment>();
            this.LifeRenewals = new HashSet<LifeRenewal>();
            this.LifeUserPolicies = new HashSet<LifeUserPolicy>();
        }
    
        public int Id { get; set; }
        public string UserID { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public System.DateTime Dob { get; set; }
        public int Age { get; set; }
        public decimal SumAssured { get; set; }
        public int Tenor { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> Frequency { get; set; }
        public string FrquencyName { get; set; }
        public string Address { get; set; }
        public string Beneficiary { get; set; }
        public string Relationship { get; set; }
        public Nullable<bool> Question1 { get; set; }
        public Nullable<bool> Question2 { get; set; }
        public Nullable<bool> Question3 { get; set; }
        public Nullable<bool> IsRenewal { get; set; }
        public decimal Premium { get; set; }
        public string Reference { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvUserPolicy> InvUserPolicies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LifePayment> LifePayments { get; set; }
        public virtual LifeProduct LifeProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LifeRenewal> LifeRenewals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LifeUserPolicy> LifeUserPolicies { get; set; }
    }
}
