//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarineQuote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MarineQuote()
        {
            this.MarinePayments = new HashSet<MarinePayment>();
            this.MarineRenewals = new HashSet<MarineRenewal>();
            this.MarineUserPolicies = new HashSet<MarineUserPolicy>();
        }
    
        public int Id { get; set; }
        public string UserID { get; set; }
        public int ClauseId { get; set; }
        public string AssuredInterest { get; set; }
        public decimal InvoiceValue { get; set; }
        public string CurrencyType { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public string ProformaInvoice { get; set; }
        public Nullable<System.DateTime> ProformaInvoiceDate { get; set; }
        public string SailingFrom { get; set; }
        public string SailingTo { get; set; }
        public string PackageType { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public Nullable<decimal> Premium { get; set; }
        public Nullable<bool> IsRenewal { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<decimal> SumInsured { get; set; }
        public string Reference { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Clause Clause { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarinePayment> MarinePayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarineRenewal> MarineRenewals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarineUserPolicy> MarineUserPolicies { get; set; }
    }
}
