//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarineFile
    {
        public int Id { get; set; }
        public string UserID { get; set; }
        public byte[] ProformaFile { get; set; }
        public string ProformaFileExt { get; set; }
        public byte[] CACFile { get; set; }
        public string CACFileExt { get; set; }
        public Nullable<bool> IsAchived { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public string TransRef { get; set; }
        public string FileType { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
