//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSME_MSME
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string AccNo { get; set; }
        public int StatLevel { get; set; }
        public string AssetDesc { get; set; }
        public string DbxaOption { get; set; }
        public string LocationOfAsset { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string StatusText { get; set; }
        public System.DateTime Postedon { get; set; }
        public Nullable<System.DateTime> Authorizedon { get; set; }
        public string AuthorizedBy { get; set; }
        public Nullable<bool> IsSeen { get; set; }
        public Nullable<bool> IsSeenDiamond { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public byte[] up_tsize { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
