//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NIIDMotor
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int QuoteID { get; set; }
        public string PolicyNo { get; set; }
        public string ResponseDescription { get; set; }
        public System.DateTime UploadTime { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Quote Quote { get; set; }
    }
}
