//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSIA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NSIAMobileEntities : DbContext
    {
        public NSIAMobileEntities()
            : base("name=NSIAMobileEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AntTable> AntTables { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
        public virtual DbSet<BurglaryPayment> BurglaryPayments { get; set; }
        public virtual DbSet<BurglaryQuote> BurglaryQuotes { get; set; }
        public virtual DbSet<BurglaryRenewal> BurglaryRenewals { get; set; }
        public virtual DbSet<BurglaryUserPolicy> BurglaryUserPolicies { get; set; }
        public virtual DbSet<BusinessClass> BusinessClasses { get; set; }
        public virtual DbSet<Carmake> Carmakes { get; set; }
        public virtual DbSet<Carmodel> Carmodels { get; set; }
        public virtual DbSet<ClaimsBurglary> ClaimsBurglaries { get; set; }
        public virtual DbSet<ClaimsDocument> ClaimsDocuments { get; set; }
        public virtual DbSet<ClaimsFire> ClaimsFires { get; set; }
        public virtual DbSet<ClaimsLife> ClaimsLives { get; set; }
        public virtual DbSet<ClaimsMarine> ClaimsMarines { get; set; }
        public virtual DbSet<ClaimsMotor> ClaimsMotors { get; set; }
        public virtual DbSet<Clause> Clauses { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<CustDocument> CustDocuments { get; set; }
        public virtual DbSet<CustDocumentMotor> CustDocumentMotors { get; set; }
        public virtual DbSet<DeviceClaim> DeviceClaims { get; set; }
        public virtual DbSet<DeviceDocument> DeviceDocuments { get; set; }
        public virtual DbSet<DevicePayment> DevicePayments { get; set; }
        public virtual DbSet<DeviceQuote> DeviceQuotes { get; set; }
        public virtual DbSet<DeviceRenewal> DeviceRenewals { get; set; }
        public virtual DbSet<DeviceUserPolicy> DeviceUserPolicies { get; set; }
        public virtual DbSet<DstvHomeType> DstvHomeTypes { get; set; }
        public virtual DbSet<DstvPersonalOption> DstvPersonalOptions { get; set; }
        public virtual DbSet<DstvPolicy> DstvPolicies { get; set; }
        public virtual DbSet<DstvPremiumDetail> DstvPremiumDetails { get; set; }
        public virtual DbSet<DstvSubscriberIdentificationType> DstvSubscriberIdentificationTypes { get; set; }
        public virtual DbSet<DstvSubscriber> DstvSubscribers { get; set; }
        public virtual DbSet<DstvSubscriberTitle> DstvSubscriberTitles { get; set; }
        public virtual DbSet<DstvTransactionPaymentsDetail> DstvTransactionPaymentsDetails { get; set; }
        public virtual DbSet<DstvTransaction> DstvTransactions { get; set; }
        public virtual DbSet<EducationTable> EducationTables { get; set; }
        public virtual DbSet<Endownment> Endownments { get; set; }
        public virtual DbSet<ExchangeRate> ExchangeRates { get; set; }
        public virtual DbSet<FirePayment> FirePayments { get; set; }
        public virtual DbSet<FireQuote> FireQuotes { get; set; }
        public virtual DbSet<FireRenewal> FireRenewals { get; set; }
        public virtual DbSet<FireUserPolicy> FireUserPolicies { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<GroupRole> GroupRoles { get; set; }
        public virtual DbSet<hhh> hhhs { get; set; }
        public virtual DbSet<InvestLinkFile> InvestLinkFiles { get; set; }
        public virtual DbSet<InvestLinkQuote> InvestLinkQuotes { get; set; }
        public virtual DbSet<InvestPayment> InvestPayments { get; set; }
        public virtual DbSet<InvRenewal> InvRenewals { get; set; }
        public virtual DbSet<InvUserPolicy> InvUserPolicies { get; set; }
        public virtual DbSet<LGA> LGAs { get; set; }
        public virtual DbSet<LifePayment> LifePayments { get; set; }
        public virtual DbSet<LifeProduct> LifeProducts { get; set; }
        public virtual DbSet<LifeQuote> LifeQuotes { get; set; }
        public virtual DbSet<LifeRenewal> LifeRenewals { get; set; }
        public virtual DbSet<LifeUpload> LifeUploads { get; set; }
        public virtual DbSet<LifeUserPolicy> LifeUserPolicies { get; set; }
        public virtual DbSet<MarineFile> MarineFiles { get; set; }
        public virtual DbSet<MarinePayment> MarinePayments { get; set; }
        public virtual DbSet<MarineQuote> MarineQuotes { get; set; }
        public virtual DbSet<MarineRenewal> MarineRenewals { get; set; }
        public virtual DbSet<MarineUserPolicy> MarineUserPolicies { get; set; }
        public virtual DbSet<MSME_MSME> MSME_MSME { get; set; }
        public virtual DbSet<MyPool> MyPools { get; set; }
        public virtual DbSet<NIIDMotor> NIIDMotors { get; set; }
        public virtual DbSet<NsiaAdmin> NsiaAdmins { get; set; }
        public virtual DbSet<NsiaDstvAdmin> NsiaDstvAdmins { get; set; }
        public virtual DbSet<PaymentDetail> PaymentDetails { get; set; }
        public virtual DbSet<PolicyPool> PolicyPools { get; set; }
        public virtual DbSet<ProfileImage> ProfileImages { get; set; }
        public virtual DbSet<Promo> Promos { get; set; }
        public virtual DbSet<Quote> Quotes { get; set; }
        public virtual DbSet<Renewal> Renewals { get; set; }
        public virtual DbSet<ResponseLog> ResponseLogs { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Segment> Segments { get; set; }
        public virtual DbSet<SiriusMotorRenewal> SiriusMotorRenewals { get; set; }
        public virtual DbSet<StatesDB> StatesDBs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TermRateAnnual> TermRateAnnuals { get; set; }
        public virtual DbSet<TermRateSingle> TermRateSingles { get; set; }
        public virtual DbSet<UserClaim> UserClaims { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<UserPolicy> UserPolicies { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<VehicleDetail> VehicleDetails { get; set; }
        public virtual DbSet<WebClaim> WebClaims { get; set; }
        public virtual DbSet<AggregatedCounter> AggregatedCounters { get; set; }
        public virtual DbSet<Counter> Counters { get; set; }
        public virtual DbSet<Hash> Hashes { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobParameter> JobParameters { get; set; }
        public virtual DbSet<JobQueue> JobQueues { get; set; }
        public virtual DbSet<List> Lists { get; set; }
        public virtual DbSet<Schema> Schemata { get; set; }
        public virtual DbSet<Server> Servers { get; set; }
        public virtual DbSet<Set> Sets { get; set; }
        public virtual DbSet<State> States { get; set; }
    }
}
