//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermRateAnnual
    {
        public int Id { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<decimal> Term1 { get; set; }
        public Nullable<decimal> Term2 { get; set; }
        public Nullable<decimal> Term3 { get; set; }
        public Nullable<decimal> Term4 { get; set; }
        public Nullable<decimal> Term5 { get; set; }
        public Nullable<decimal> Term6 { get; set; }
        public Nullable<decimal> Term7 { get; set; }
        public Nullable<decimal> Term8 { get; set; }
        public Nullable<decimal> Term9 { get; set; }
        public Nullable<decimal> Term10 { get; set; }
        public Nullable<decimal> Term11 { get; set; }
        public Nullable<decimal> Term12 { get; set; }
        public Nullable<decimal> Term13 { get; set; }
        public Nullable<decimal> Term14 { get; set; }
        public Nullable<decimal> Term15 { get; set; }
        public Nullable<decimal> Term16 { get; set; }
        public Nullable<decimal> Term17 { get; set; }
        public Nullable<decimal> Term18 { get; set; }
        public Nullable<decimal> Term19 { get; set; }
        public Nullable<decimal> Term20 { get; set; }
        public Nullable<decimal> Term21 { get; set; }
        public Nullable<decimal> Term22 { get; set; }
        public Nullable<decimal> Term23 { get; set; }
        public Nullable<decimal> Term24 { get; set; }
        public Nullable<decimal> Term25 { get; set; }
        public Nullable<decimal> Term26 { get; set; }
        public Nullable<decimal> Term27 { get; set; }
        public Nullable<decimal> Term28 { get; set; }
        public Nullable<decimal> Term29 { get; set; }
        public Nullable<decimal> Term30 { get; set; }
    }
}
