//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserClaim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserClaim()
        {
            this.ClaimsDocuments = new HashSet<ClaimsDocument>();
        }
    
        public int ID { get; set; }
        public string UserId { get; set; }
        public int RefID { get; set; }
        public string AccidentPlace { get; set; }
        public Nullable<System.DateTime> AccidentDate { get; set; }
        public string AccidentSummary { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClaimsDocument> ClaimsDocuments { get; set; }
        public virtual UserPolicy UserPolicy { get; set; }
    }
}
