//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebClaim
    {
        public int Id { get; set; }
        public string bizclassId { get; set; }
        public string bizclass { get; set; }
        public string policyno { get; set; }
        public string description { get; set; }
        public string location { get; set; }
        public System.DateTime lossDate { get; set; }
        public string Email { get; set; }
        public string Phoneno { get; set; }
    }
}
